from __future__ import annotations

from datetime import UTC, datetime, timedelta

from incident_response_copilot.models import (
    EvidenceItem,
    Incident,
    IncidentStatus,
    PlaybookStep,
    ResponseTask,
    Severity,
    TaskStatus,
    TimelineEvent,
)

BASE_TIME = datetime(2026, 5, 8, 14, 0, tzinfo=UTC)


def demo_incidents() -> list[Incident]:
    return [
        Incident(
            id="inc_siem_bruteforce",
            title="Credential stuffing spike",
            severity=Severity.HIGH,
            status=IncidentStatus.CONTAINMENT,
            started_at=BASE_TIME,
            summary="Wazuh-style alerts show repeated failed login attempts against admin accounts.",
        ),
        Incident(
            id="inc_k8s_policy_gap",
            title="Unexpected pod egress",
            severity=Severity.MEDIUM,
            status=IncidentStatus.TRIAGE,
            started_at=BASE_TIME + timedelta(minutes=10),
            summary="Kubernetes traffic sample indicates egress not covered by current NetworkPolicy.",
        ),
        Incident(
            id="inc_malware_callback",
            title="Sandbox callback indicator",
            severity=Severity.CRITICAL,
            status=IncidentStatus.CONTAINMENT,
            started_at=BASE_TIME + timedelta(minutes=20),
            summary="Malware sandbox report contains suspicious callback and YARA fallback warning.",
        ),
    ]


def demo_evidence() -> list[EvidenceItem]:
    return [
        EvidenceItem(
            id="ev_failed_logins",
            incident_id="inc_siem_bruteforce",
            source="siem.alert",
            description="43 failed logins from one ASN in 12 minutes",
            confidence=0.91,
        ),
        EvidenceItem(
            id="ev_redis_degraded",
            incident_id="inc_siem_bruteforce",
            source="cache.metadata",
            description="Redis dedupe degraded; review duplicate alert count",
            confidence=0.72,
        ),
        EvidenceItem(
            id="ev_k8s_flow",
            incident_id="inc_k8s_policy_gap",
            source="network.flow",
            description="Pod namespace payments connected to external IP",
            confidence=0.83,
        ),
        EvidenceItem(
            id="ev_cuckoo_callback",
            incident_id="inc_malware_callback",
            source="sandbox.report",
            description="Cuckoo task observed callback to newly registered domain",
            confidence=0.88,
        ),
        EvidenceItem(
            id="ev_yara_fallback",
            incident_id="inc_malware_callback",
            source="yara.metadata",
            description="YARA rule generated by fallback heuristic and needs review",
            confidence=0.64,
        ),
    ]


def demo_timeline() -> list[TimelineEvent]:
    rows = []
    for i, incident in enumerate(demo_incidents()):
        rows.append(
            TimelineEvent(
                id=f"tl_{incident.id}_open",
                incident_id=incident.id,
                timestamp=incident.started_at,
                actor="copilot",
                message="Opened incident from correlated evidence.",
            )
        )
        rows.append(
            TimelineEvent(
                id=f"tl_{incident.id}_review",
                incident_id=incident.id,
                timestamp=incident.started_at + timedelta(minutes=5 + i),
                actor="analyst",
                message="Marked recommendation for human review before containment.",
            )
        )
    return rows


def demo_tasks() -> list[ResponseTask]:
    return [
        ResponseTask(
            id="task_lock_accounts",
            incident_id="inc_siem_bruteforce",
            title="Review and lock targeted admin accounts",
            status=TaskStatus.IN_PROGRESS,
            owner="identity",
            requires_approval=True,
        ),
        ResponseTask(
            id="task_policy_draft",
            incident_id="inc_k8s_policy_gap",
            title="Draft NetworkPolicy in dry-run mode",
            status=TaskStatus.TODO,
            owner="platform",
            requires_approval=True,
        ),
        ResponseTask(
            id="task_isolate_sample",
            incident_id="inc_malware_callback",
            title="Keep sample isolated and preserve sandbox artifacts",
            status=TaskStatus.DONE,
            owner="malware",
            requires_approval=False,
        ),
        ResponseTask(
            id="task_block_ioc",
            incident_id="inc_malware_callback",
            title="Propose IOC blocklist update",
            status=TaskStatus.BLOCKED,
            owner="soc",
            requires_approval=True,
        ),
    ]


def demo_playbook() -> list[PlaybookStep]:
    return [
        PlaybookStep(
            id=f"pb_{incident.id}_1",
            incident_id=incident.id,
            title="Validate evidence",
            rationale="Confirm source reliability and degraded metadata before action.",
            human_review_note="Do not automate containment from demo evidence alone.",
        )
        for incident in demo_incidents()
    ]
